[tasks.fmt_check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all","--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets","--", "-D", "warnings"]

[tasks.checks]
dependencies = [
    "fmt_check",
    "clippy",
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]