//! The textual LLVM IR emitter.
//!
//! One [`hir::Function`] becomes one `define`, one local becomes one `alloca`
//! in the entry block plus loads and stores everywhere else. `clang -O2` runs
//! `mem2reg`, which turns those allocas back into SSA registers, so the emitter
//! never has to build phi nodes itself (DESIGN §6.2).

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write;

use typhoon_sema::hir;
use typhoon_sema::types::TypeId;

/// The smallest `int`, whose negation and division by `-1` both wrap.
const I64_MIN: &str = "-9223372036854775808";

/// Emits the whole program as one LLVM module.
pub fn emit_module(program: &hir::Program) -> String {
    let mut emitter = Emitter::new(program);
    emitter.emit_program();
    emitter.finish()
}

/// Emitter state: module-level tables plus the function being emitted.
struct Emitter<'p> {
    program: &'p hir::Program,
    /// Global definitions (string literals, panic messages).
    globals: String,
    /// The runtime and intrinsic declarations actually used.
    decls: BTreeSet<&'static str>,
    /// String literal contents to the global holding them.
    strings: HashMap<String, String>,
    /// Panic messages to `(global, length)`.
    panics: HashMap<String, (String, usize)>,
    next_global: u32,
    /// Every emitted function.
    functions: String,

    // -- per function -----------------------------------------------------
    allocas: String,
    body: String,
    tmp: u32,
    lbl: u32,
    slots: Vec<String>,
    terminated: bool,
    /// `(break target, continue target)` for every enclosing loop.
    loops: Vec<(String, String)>,
}

impl<'p> Emitter<'p> {
    fn new(program: &'p hir::Program) -> Emitter<'p> {
        Emitter {
            program,
            globals: String::new(),
            decls: BTreeSet::new(),
            strings: HashMap::new(),
            panics: HashMap::new(),
            next_global: 0,
            functions: String::new(),
            allocas: String::new(),
            body: String::new(),
            tmp: 0,
            lbl: 0,
            slots: Vec::new(),
            terminated: false,
            loops: Vec::new(),
        }
    }

    fn finish(self) -> String {
        let mut out = String::new();
        out.push_str("; Generated by the typhoon compiler (DESIGN.md section 6.2).\n");
        out.push_str("; LLVM 18+ textual IR, opaque pointers.\n\n");
        if !self.globals.is_empty() {
            out.push_str(&self.globals);
            out.push('\n');
        }
        out.push_str(&self.functions);
        if !self.decls.is_empty() {
            out.push_str("\n; -- runtime and intrinsics ---------------------------------------\n");
            for decl in &self.decls {
                out.push_str(decl);
                out.push('\n');
            }
        }
        out
    }

    // -- module -----------------------------------------------------------

    fn emit_program(&mut self) {
        for (index, func) in self.program.functions.iter().enumerate() {
            self.emit_function(hir::FuncId(index as u32), func);
        }
        self.emit_entry_point();
    }

    /// The C `main`: start the runtime, run the user's `main`, flush and exit.
    fn emit_entry_point(&mut self) {
        let user_main = &self.program.function(self.program.main).symbol;
        self.decls.insert("declare void @ty_rt_init()");
        self.decls
            .insert("declare void @ty_rt_exit(i32) noreturn nounwind");
        let _ = write!(
            self.functions,
            "\n; the process entry point\n\
             define i32 @main() nounwind {{\n\
             entry:\n\
             \x20 call void @ty_rt_init()\n\
             \x20 call void @{user_main}()\n\
             \x20 call void @ty_rt_exit(i32 0)\n\
             \x20 unreachable\n\
             }}\n"
        );
    }

    fn emit_function(&mut self, id: hir::FuncId, func: &'p hir::Function) {
        self.allocas.clear();
        self.body.clear();
        self.tmp = 0;
        self.lbl = 0;
        self.terminated = false;
        self.loops.clear();
        self.slots = func
            .locals
            .iter()
            .map(|local| format!("%{}.addr", local.name))
            .collect();

        // Entry block: one alloca per local, then the incoming parameters.
        for (index, local) in func.locals.iter().enumerate() {
            let ty = llvm_ty(local.ty);
            let _ = writeln!(
                self.allocas,
                "  {} = alloca {ty}, align {}",
                self.slots[index],
                align_of(local.ty)
            );
        }
        for param in &func.params {
            let local = &func.locals[param.index()];
            let ty = llvm_ty(local.ty);
            let _ = writeln!(
                self.allocas,
                "  store {ty} %{}.arg, ptr {}, align {}",
                local.name,
                self.slots[param.index()],
                align_of(local.ty)
            );
        }

        self.block(func, &func.body);

        // Fall off the end: `main` and other unit functions return, a function
        // with a return type cannot get here (sema proved it returns).
        if !self.terminated {
            if func.ret == TypeId::UNIT {
                self.emit("ret void");
            } else {
                self.emit("unreachable");
            }
        }

        let params: Vec<String> = func
            .params
            .iter()
            .map(|id| {
                let local = &func.locals[id.index()];
                format!("{} %{}.arg", llvm_ty(local.ty), local.name)
            })
            .collect();
        let signature: Vec<String> = func
            .params
            .iter()
            .map(|id| {
                let local = &func.locals[id.index()];
                format!("{}: {}", local.name, self.program.types.name(local.ty))
            })
            .collect();
        let _ = write!(
            self.functions,
            "\n; fn {}({}) -> {}\ndefine internal {} @{}({}) nounwind {{\nentry:\n{}{}}}\n",
            func.name,
            signature.join(", "),
            self.program.types.name(func.ret),
            llvm_ret_ty(func.ret),
            func.symbol,
            params.join(", "),
            self.allocas,
            self.body,
        );
        let _ = id;
    }

    // -- emitting primitives ----------------------------------------------

    /// Appends one instruction, opening a fresh block first when the current
    /// one already ended.
    fn emit(&mut self, text: &str) {
        if self.terminated {
            let label = self.fresh_label("dead");
            let _ = write!(self.body, "\n{label}:\n");
            self.terminated = false;
        }
        let _ = writeln!(self.body, "  {text}");
    }

    fn comment(&mut self, text: &str) {
        let _ = writeln!(self.body, "  ; {text}");
    }

    fn start_block(&mut self, label: &str) {
        let _ = write!(self.body, "\n{label}:\n");
        self.terminated = false;
    }

    fn br(&mut self, label: &str) {
        self.emit(&format!("br label %{label}"));
        self.terminated = true;
    }

    fn cond_br(&mut self, cond: &str, then: &str, else_: &str) {
        self.emit(&format!("br i1 {cond}, label %{then}, label %{else_}"));
        self.terminated = true;
    }

    fn fresh(&mut self) -> String {
        self.tmp += 1;
        format!("%t{}", self.tmp)
    }

    fn fresh_label(&mut self, base: &str) -> String {
        self.lbl += 1;
        format!("{base}.{}", self.lbl)
    }

    /// An `alloca` in the entry block, for the result of a short-circuit
    /// operator.
    fn scratch(&mut self, ty: &str, align: u32) -> String {
        self.lbl += 1;
        let name = format!("%scratch.{}", self.lbl);
        let _ = writeln!(self.allocas, "  {name} = alloca {ty}, align {align}");
        name
    }

    // -- statements -------------------------------------------------------

    fn block(&mut self, func: &'p hir::Function, block: &hir::Block) {
        for stmt in &block.stmts {
            self.stmt(func, stmt);
        }
    }

    fn stmt(&mut self, func: &'p hir::Function, stmt: &hir::Stmt) {
        match stmt {
            hir::Stmt::Assign { local, value } => {
                let ty = func.locals[local.index()].ty;
                let value = self.expr(func, value);
                let slot = self.slots[local.index()].clone();
                self.emit(&format!(
                    "store {} {value}, ptr {slot}, align {}",
                    llvm_ty(ty),
                    align_of(ty)
                ));
            }
            hir::Stmt::Expr(expr) => {
                self.expr(func, expr);
            }
            hir::Stmt::Return(None) => {
                self.emit("ret void");
                self.terminated = true;
            }
            hir::Stmt::Return(Some(value)) => {
                let ty = llvm_ty(value.ty);
                let value = self.expr(func, value);
                self.emit(&format!("ret {ty} {value}"));
                self.terminated = true;
            }
            hir::Stmt::If { cond, then, else_ } => self.emit_if(func, cond, then, else_.as_ref()),
            hir::Stmt::While { cond, body } => self.emit_while(func, cond, body),
            hir::Stmt::ForRange {
                var,
                start,
                stop,
                step,
                body,
            } => self.emit_for(func, *var, start, stop, step, body),
            hir::Stmt::Break => {
                let target = self.loops.last().expect("`break` inside a loop").0.clone();
                self.br(&target);
            }
            hir::Stmt::Continue => {
                let target = self
                    .loops
                    .last()
                    .expect("`continue` inside a loop")
                    .1
                    .clone();
                self.br(&target);
            }
        }
    }

    fn emit_if(
        &mut self,
        func: &'p hir::Function,
        cond: &hir::Expr,
        then: &hir::Block,
        else_: Option<&hir::Block>,
    ) {
        let cond = self.expr(func, cond);
        let then_label = self.fresh_label("if.then");
        let else_label = self.fresh_label("if.else");
        let end_label = self.fresh_label("if.end");

        self.cond_br(
            &cond,
            &then_label,
            if else_.is_some() {
                &else_label
            } else {
                &end_label
            },
        );

        self.start_block(&then_label);
        self.block(func, then);
        if !self.terminated {
            self.br(&end_label);
        }

        if let Some(else_) = else_ {
            self.start_block(&else_label);
            self.block(func, else_);
            if !self.terminated {
                self.br(&end_label);
            }
        }

        self.start_block(&end_label);
    }

    fn emit_while(&mut self, func: &'p hir::Function, cond: &hir::Expr, body: &hir::Block) {
        let head = self.fresh_label("while.cond");
        let body_label = self.fresh_label("while.body");
        let end = self.fresh_label("while.end");

        self.br(&head);
        self.start_block(&head);
        let cond = self.expr(func, cond);
        self.cond_br(&cond, &body_label, &end);

        self.start_block(&body_label);
        self.loops.push((end.clone(), head.clone()));
        self.block(func, body);
        self.loops.pop();
        if !self.terminated {
            self.br(&head);
        }

        self.start_block(&end);
    }

    /// `for i in range(start, stop, step)` as a counting loop that allocates
    /// nothing (DESIGN §3.5).
    fn emit_for(
        &mut self,
        func: &'p hir::Function,
        var: hir::LocalId,
        start: &hir::Expr,
        stop: &hir::Expr,
        step: &hir::Expr,
        body: &hir::Block,
    ) {
        let start_value = self.expr(func, start);
        let stop_value = self.expr(func, stop);
        let literal_step = match step.kind {
            hir::ExprKind::Int(v) => Some(v),
            _ => None,
        };
        let step_value = self.expr(func, step);

        match literal_step {
            Some(0) => {
                self.panic("range() step must not be zero");
                return;
            }
            None => {
                let zero = self.fresh();
                self.emit(&format!("{zero} = icmp eq i64 {step_value}, 0"));
                self.panic_if(&zero, "range() step must not be zero");
            }
            Some(_) => {}
        }

        let iv = {
            self.lbl += 1;
            let name = format!("%for.iv.{}", self.lbl);
            let _ = writeln!(self.allocas, "  {name} = alloca i64, align 8");
            name
        };
        self.emit(&format!("store i64 {start_value}, ptr {iv}, align 8"));

        let head = self.fresh_label("for.cond");
        let body_label = self.fresh_label("for.body");
        let next = self.fresh_label("for.step");
        let end = self.fresh_label("for.end");

        self.br(&head);
        self.start_block(&head);
        let i = self.fresh();
        self.emit(&format!("{i} = load i64, ptr {iv}, align 8"));
        // A literal step decides the direction of the test at compile time.
        let cond = match literal_step {
            Some(v) if v > 0 => {
                let c = self.fresh();
                self.emit(&format!("{c} = icmp slt i64 {i}, {stop_value}"));
                c
            }
            Some(_) => {
                let c = self.fresh();
                self.emit(&format!("{c} = icmp sgt i64 {i}, {stop_value}"));
                c
            }
            None => {
                let up = self.fresh();
                let lt = self.fresh();
                let gt = self.fresh();
                let c = self.fresh();
                self.emit(&format!("{up} = icmp sgt i64 {step_value}, 0"));
                self.emit(&format!("{lt} = icmp slt i64 {i}, {stop_value}"));
                self.emit(&format!("{gt} = icmp sgt i64 {i}, {stop_value}"));
                self.emit(&format!("{c} = select i1 {up}, i1 {lt}, i1 {gt}"));
                c
            }
        };
        self.cond_br(&cond, &body_label, &end);

        self.start_block(&body_label);
        let slot = self.slots[var.index()].clone();
        self.emit(&format!("store i64 {i}, ptr {slot}, align 8"));
        self.loops.push((end.clone(), next.clone()));
        self.block(func, body);
        self.loops.pop();
        if !self.terminated {
            self.br(&next);
        }

        self.start_block(&next);
        let cur = self.fresh();
        let inc = self.fresh();
        self.emit(&format!("{cur} = load i64, ptr {iv}, align 8"));
        self.emit(&format!("{inc} = add i64 {cur}, {step_value}"));
        self.emit(&format!("store i64 {inc}, ptr {iv}, align 8"));
        self.br(&head);

        self.start_block(&end);
    }

    // -- panics -----------------------------------------------------------

    /// Emits an unconditional panic; the current block ends here.
    fn panic(&mut self, message: &str) {
        let (global, len) = self.panic_message(message);
        self.decls
            .insert("declare void @ty_panic(ptr, i64) noreturn nounwind");
        self.emit(&format!("call void @ty_panic(ptr {global}, i64 {len})"));
        self.emit("unreachable");
        self.terminated = true;
    }

    /// Emits `if cond: panic(message)`.
    fn panic_if(&mut self, cond: &str, message: &str) {
        let fail = self.fresh_label("panic");
        let ok = self.fresh_label("cont");
        self.cond_br(cond, &fail, &ok);
        self.start_block(&fail);
        self.panic(message);
        self.start_block(&ok);
    }

    fn panic_message(&mut self, message: &str) -> (String, usize) {
        if let Some(entry) = self.panics.get(message) {
            return entry.clone();
        }
        let name = format!("@panic.{}", self.next_global);
        self.next_global += 1;
        let bytes = message.as_bytes();
        let _ = writeln!(
            self.globals,
            "{name} = private unnamed_addr constant [{} x i8] c\"{}\", align 1",
            bytes.len(),
            escape(bytes)
        );
        let entry = (name, bytes.len());
        self.panics.insert(message.to_string(), entry.clone());
        entry
    }

    /// Interns a string literal as a `TyStr` header followed by its bytes.
    fn string_literal(&mut self, text: &str) -> String {
        if let Some(name) = self.strings.get(text) {
            return name.clone();
        }
        let name = format!("@str.{}", self.next_global);
        self.next_global += 1;
        let bytes = text.as_bytes();
        let _ = writeln!(
            self.globals,
            "{name} = private unnamed_addr constant {{ i64, [{n} x i8] }} \
             {{ i64 {n}, [{n} x i8] c\"{}\" }}, align 8",
            escape(bytes),
            n = bytes.len()
        );
        self.strings.insert(text.to_string(), name.clone());
        name
    }
}

/// Escapes bytes for an LLVM `c"..."` constant.
fn escape(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        if b == b'"' || b == b'\\' || !(0x20..0x7f).contains(&b) {
            let _ = write!(out, "\\{b:02X}");
        } else {
            out.push(b as char);
        }
    }
    out
}

/// The LLVM type a typhoon value of type `ty` is held in.
fn llvm_ty(ty: TypeId) -> &'static str {
    match ty {
        TypeId::INT => "i64",
        TypeId::FLOAT => "double",
        TypeId::BOOL => "i1",
        TypeId::STR => "ptr",
        _ => "void",
    }
}

/// The LLVM return type for a typhoon return type.
fn llvm_ret_ty(ty: TypeId) -> &'static str {
    if ty == TypeId::UNIT {
        "void"
    } else {
        llvm_ty(ty)
    }
}

fn align_of(ty: TypeId) -> u32 {
    match ty {
        TypeId::BOOL => 1,
        _ => 8,
    }
}

/// Formats a `f64` so that LLVM parses it back bit for bit.
///
/// Rust's shortest round-trip form is used when it is finite (LLVM parses
/// decimals with correct rounding), except that LLVM needs a `.` or a hex
/// form: `1e300` alone would be read as an integer.
pub(crate) fn float_literal(value: f64) -> String {
    if !value.is_finite() {
        return format!("0x{:016X}", value.to_bits());
    }
    let text = format!("{value:?}");
    if text.contains('.') {
        return text;
    }
    match text.split_once('e') {
        Some((mantissa, exponent)) => format!("{mantissa}.0e{exponent}"),
        None => format!("{text}.0"),
    }
}

mod exprs;
