[package]
name = "typhoon"
version = "0.1.0"
authors = ["Kilerd Chan <blove694@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
env_logger = "0.9.0"
core = {path="../core"}
