[package]
name = "ast"
version = "0.1.0"
authors = ["Kilerd Chan <blove694@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.2.1", features = ["serde", "v4"] }
log = "0.4.14"

