//! The WebAssembly target: `typhoon build --target wasm`.
//!
//! See `docs/DESIGN.md` §6.2.1. A Typhoon wasm build is three files:
//!
//! ```text
//! <name>.wasm       the program, from typhoon-codegen-wasm
//! typhoon_rt.wasm   crates/runtime built for wasm32-unknown-unknown
//! <name>.js         an ES module that instantiates both and runs _start
//! ```
//!
//! The runtime module is compiled by this crate's build script and embedded
//! here, so producing a wasm build needs nothing on the machine but the
//! compiler itself. The loader is [`LOADER_JS`], the same file the browser
//! playground uses, with a per-program tail appended.

use std::path::{Path, PathBuf};

use crate::DriverError;

/// The shared JS loader (`crates/driver/assets/loader.js`).
///
/// `web/build.sh` copies the same file to `web/pkg/loader.js`, so the browser
/// playground and a CLI build run programs through identical code.
pub const LOADER_JS: &str = include_str!("../assets/loader.js");

/// File name of the runtime module inside a wasm build.
pub const RUNTIME_WASM_NAME: &str = "typhoon_rt.wasm";

#[cfg(has_wasm_runtime)]
const RUNTIME_WASM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/typhoon_rt.wasm"));

/// The Typhoon runtime compiled for `wasm32-unknown-unknown`.
///
/// # Errors
///
/// [`DriverError::Toolchain`] when this compiler was built without the wasm
/// target installed, with the `rustup` command that fixes it.
pub fn runtime_module() -> Result<&'static [u8], DriverError> {
    #[cfg(has_wasm_runtime)]
    {
        Ok(RUNTIME_WASM)
    }
    #[cfg(not(has_wasm_runtime))]
    {
        Err(DriverError::Toolchain(
            "this compiler was built without the WebAssembly runtime\n\
             help: install the wasm target with `rustup target add wasm32-unknown-unknown`, \
             then rebuild typhoon"
                .to_string(),
        ))
    }
}

/// Whether this build can produce wasm programs.
pub fn is_available() -> bool {
    cfg!(has_wasm_runtime)
}

/// Compiles Typhoon source to a binary wasm module.
///
/// # Errors
///
/// [`DriverError::Compile`] with the rendered diagnostics.
pub fn compile_to_wasm(name: &str, src: &str) -> Result<Vec<u8>, DriverError> {
    typhoon_codegen_wasm::compile_to_wasm(name, src).map_err(DriverError::Compile)
}

/// The files written by [`write_package`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WasmPackage {
    /// The compiled program.
    pub program: PathBuf,
    /// The runtime module it imports from.
    pub runtime: PathBuf,
    /// The ES-module loader that runs it.
    pub loader: PathBuf,
    /// The `README.txt` explaining how to run it.
    pub readme: PathBuf,
}

/// Writes a runnable wasm build of `wasm` into `dir`, naming its files after
/// `stem`.
///
/// # Errors
///
/// [`DriverError::Io`] if a file cannot be written, [`DriverError::Toolchain`]
/// if this compiler has no embedded runtime.
pub fn write_package(stem: &str, wasm: &[u8], dir: &Path) -> Result<WasmPackage, DriverError> {
    let runtime = runtime_module()?;
    std::fs::create_dir_all(dir)?;

    let package = WasmPackage {
        program: dir.join(format!("{stem}.wasm")),
        runtime: dir.join(RUNTIME_WASM_NAME),
        loader: dir.join(format!("{stem}.js")),
        readme: dir.join("README.txt"),
    };
    std::fs::write(&package.program, wasm)?;
    std::fs::write(&package.runtime, runtime)?;
    std::fs::write(&package.loader, program_loader(stem))?;
    std::fs::write(&package.readme, readme(stem))?;
    Ok(package)
}

/// The `<name>.js` of a wasm build: the shared loader plus a tail that knows
/// where this program's two modules are and what to do when Node runs the file
/// directly.
pub fn program_loader(stem: &str) -> String {
    format!(
        "{LOADER_JS}\n\
         // --------------------------------------------------------------------------\n\
         // Generated by `typhoon build --target wasm` for `{stem}.ty`.\n\
         \n\
         /** URL of the Typhoon runtime module. */\n\
         export const runtimeUrl = new URL(\"./{RUNTIME_WASM_NAME}\", import.meta.url);\n\
         \n\
         /** URL of the compiled program. */\n\
         export const programUrl = new URL(\"./{stem}.wasm\", import.meta.url);\n\
         \n\
         /**\n\
         \x20* Runs the program and resolves to its exit code.\n\
         \x20*\n\
         \x20* @param {{object}} [options]\n\
         \x20* @param {{(text: string) => void}} [options.stdout]\n\
         \x20* @param {{(text: string) => void}} [options.stderr]\n\
         \x20*/\n\
         export async function run(options = {{}}) {{\n\
         \x20 const stdout = options.stdout ?? ((text) => writeStandard(1, text));\n\
         \x20 const stderr = options.stderr ?? ((text) => writeStandard(2, text));\n\
         \x20 const [runtime, program] = await Promise.all([\n\
         \x20   loadWasm(runtimeUrl),\n\
         \x20   loadWasm(programUrl),\n\
         \x20 ]);\n\
         \x20 const result = await runTyphoon({{ runtime, program, stdout, stderr }});\n\
         \x20 return result.exitCode;\n\
         }}\n\
         \n\
         function writeStandard(fd, text) {{\n\
         \x20 if (typeof process !== \"undefined\" && process.stdout) {{\n\
         \x20   (fd === 2 ? process.stderr : process.stdout).write(text);\n\
         \x20 }} else {{\n\
         \x20   (fd === 2 ? console.error : console.log)(text.replace(/\\n$/, \"\"));\n\
         \x20 }}\n\
         }}\n\
         \n\
         // `node {stem}.js` runs the program and exits with its status.\n\
         if (typeof process !== \"undefined\" && process.versions && process.versions.node) {{\n\
         \x20 const {{ fileURLToPath }} = await import(\"node:url\");\n\
         \x20 const {{ realpathSync }} = await import(\"node:fs\");\n\
         \x20 // Compare real paths: Node resolves `import.meta.url` through symlinks\n\
         \x20 // (macOS `/tmp` is `/private/tmp`) while `process.argv[1]` is as typed.\n\
         \x20 const self = realpathSync(fileURLToPath(import.meta.url));\n\
         \x20 const entry = process.argv[1] ? realpathSync(process.argv[1]) : \"\";\n\
         \x20 if (entry === self) {{\n\
         \x20   process.exitCode = await run();\n\
         \x20 }}\n\
         }}\n"
    )
}

/// The `README.txt` of a wasm build.
fn readme(stem: &str) -> String {
    let program = format!("{stem}.wasm");
    let loader = format!("{stem}.js");
    let width = program.len().max(loader.len()).max(RUNTIME_WASM_NAME.len());
    let blank = "";
    format!(
        "Typhoon WebAssembly build of {stem}.ty\n\
         \n\
         Files\n\
         -----\n\
         \x20 {program:<width$}   the compiled program; it imports `env.memory` and the\n\
         \x20 {blank:<width$}   `env.ty_*` functions it calls from the runtime\n\
         \x20 {RUNTIME_WASM_NAME:<width$}   the Typhoon runtime: it owns the linear memory and\n\
         \x20 {blank:<width$}   exports the `ty_*` C ABI both backends share\n\
         \x20 {loader:<width$}   an ES module that instantiates both and runs `_start`\n\
         \n\
         Run it with Node 18 or newer\n\
         ----------------------------\n\
         \x20 node {loader}\n\
         \n\
         Or from your own code\n\
         ---------------------\n\
         \x20 import {{ run }} from \"./{loader}\";\n\
         \x20 const exitCode = await run({{ stdout: (text) => process.stdout.write(text) }});\n\
         \n\
         In a browser, serve this directory over HTTP and\n\
         ------------------------------------------------\n\
         \x20 <script type=\"module\">\n\
         \x20   import {{ run }} from \"./{loader}\";\n\
         \x20   await run({{ stdout: (text) => console.log(text) }});\n\
         \x20 </script>\n\
         \n\
         The program and the runtime share one linear memory, which is why they\n\
         have to be instantiated together and in that order. This build has no\n\
         garbage collector (DESIGN 6.2.1): memory is never reclaimed, so a\n\
         long-running allocation loop ends with `panic: out of memory`.\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_loader_is_embedded() {
        assert!(LOADER_JS.contains("export async function runTyphoon"));
        assert!(LOADER_JS.contains("host_write"));
        assert!(LOADER_JS.contains("host_exit"));
    }

    #[test]
    fn the_program_loader_names_both_modules() {
        let js = program_loader("hello");
        assert!(js.contains("export async function runTyphoon"), "{js}");
        assert!(js.contains("\"./hello.wasm\""), "{js}");
        assert!(js.contains("\"./typhoon_rt.wasm\""), "{js}");
        assert!(
            js.contains("export async function run(options = {})"),
            "{js}"
        );
        // No stray `{{` from the format string.
        assert!(!js.contains("{{"), "{js}");
        assert!(!js.contains("}}"), "{js}");
    }

    #[test]
    fn the_readme_says_how_to_run_it() {
        let text = readme("demo");
        assert!(text.contains("node demo.js"), "{text}");
        assert!(text.contains("typhoon_rt.wasm"), "{text}");
    }

    #[test]
    fn the_runtime_module_is_a_wasm_binary() {
        match runtime_module() {
            Ok(bytes) => {
                assert_eq!(&bytes[..4], b"\0asm", "not a wasm module");
                assert!(bytes.len() > 1024, "suspiciously small: {}", bytes.len());
            }
            // A build without the wasm target must still explain itself.
            Err(err) => {
                let message = err.to_string();
                assert!(message.contains("rustup target add"), "{message}");
            }
        }
    }
}
